#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage:  `basename $0` <base> <nnnn>" 1>&2
  exit 1
fi

base=$1
num=$2

list=`ls -rt`
mkdir zz$$
mv $list zz$$

cd zz$$
for old in $list
do
  if [ -f $old ]
  then
    ext=`echo $old | tr . \\\\012 | tail -1`
    mv -i $old ../`echo $base $num $ext | \
	awk '{ printf "%s-%04d.%s",$1,$2,$3 }'`
    num=$[$num+1]
  else
    mv $old ..
  fi
done

cd ..
rmdir zz$$
